name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-github-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # You can change this to a different branch if needed
          folder: out  # Output folder from Next.js build (usually 'out')

